---
- name: Install TRANA
  hosts: localhost
  become: yes
  tasks:
      - name: Update apt cache
        apt:
          update_cache=yes
          cache_valid_time=7200
      - name: Install APT packages
        apt: name=docker
