---
- name: Install TRANA
  hosts: localhost
  vars:
    base_path: "/data/trana"
    bin_path: "{{ base_path }}/bin"
    trana_path: "{{ base_path }}/trana"
    report_path: "{{ base_path }}/16s-report"
    install_path: "{{ base_path }}/install"
    run_path: "{{ base_path }}/run"
  tasks:
  - name: Clone the TRANA repo
    git:
        repo: https://github.com/genomic-medicine-sweden/TRANA.git
        dest: "{{ trana_path }}"
        clone: yes
        force: yes
        version: hotfix-20251114-fix-nanoplot-image

  - name: Run TRANA install script
    make:
        chdir: "{{ trana_path }}"
        target: install

  - name: Download pixi
    get_url:
        url: https://github.com/prefix-dev/pixi/releases/download/v0.59.0/pixi-x86_64-unknown-linux-musl.tar.gz
        dest: "{{ install_path }}"

  - name: Create bin folder
    ansible.builtin.file:
        path: "{{ bin_path }}"
        state: directory

  - name: Add bin folder to PATH
    lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        line: "PATH={{ bin_path }}:$PATH"

  - name: Unarchive pixi
    unarchive:
        src: pixi-x86_64-unknown-linux-musl.tar.gz
        dest: "{{ bin_path }}"

  - name: Create pixi environment
    shell: |
        cd "{{ trana_path }}"
        "{{ bin_path }}/pixi" init -q --no-progress --format pixi "{{ trana_path }}"
    args:
        creates: "{{ trana_path }}/pixi.toml"

  - name: Add bioconda channel to pixi environment
    lineinfile:
        path: "{{ trana_path }}/pixi.toml"
        regexp: "^channels\ "
        line: 'channels = ["conda-forge", "bioconda"]'

  - name: Install Nextflow and Singularity via Pixi
    shell: |
        "{{ bin_path }}/pixi" add --manifest-path "{{ trana_path }}/pixi.toml" nextflow singularity
    args:
        creates: "{{ trana_path }}/.pixi/envs/default/bin/nextflow"

  - name: Download the bartender GUI
    get_url:
        url: https://github.com/samuell/bartender/releases/download/v0.2.1/bartender-v0.2.1-linux-amd64.tar.gz
        dest: "{{ install_path }}"

  - name: Unarchive bartender
    unarchive:
        src: bartender-v0.2.1-linux-amd64.tar.gz
        dest: "{{ bin_path }}"

  - name: Download ontime
    get_url:
        url: https://github.com/mbhall88/ontime/releases/download/0.3.1/ontime-0.3.1-x86_64-unknown-linux-musl.tar.gz
        dest: "{{ install_path }}"

  - name: Unarchive ontime
    unarchive:
        src: ontime-0.3.1-x86_64-unknown-linux-musl.tar.gz
        dest: "{{ install_path }}"

  - name: Move ontime to destination
    copy:
        src: "{{ install_path }}/ontime-0.3.1-x86_64-unknown-linux-musl/ontime"
        dest: "{{ bin_path }}"
        mode: "a=rx"

  - name: Download 16S Report
    git:
        repo: https://github.com/AnnaNoren/tranavy.git
        dest: "{{ report_path }}"
        clone: yes
        force: yes
        version: dev

  - name: Create run folder
    ansible.builtin.file:
        path: "{{ run_path }}"
        state: directory

  - name: Create symlink to detect-and-run script
    ansible.builtin.file:
        src: "{{ install_path }}/{{ item }}"
        dest: "{{ run_path }}/{{ item }}"
        state: link
    loop:
      - detect-data-and-run.sh
      - create-reports.sh
